before_script:
    - sudo apt-get install espeak ffmpeg -y > /dev/null
    - wget --no-check-certificate -O roundup https://raw.github.com/bmizerany/roundup/a8a175a7fba9bbfb14d1025951c4b46a65e875a6/roundup.sh
    - chmod +x roundup

script: ./roundup speaker-test.sh
